### ISSUE TITLE
Better error reporting for invalid/incomplete IMS context configurations

### ISSUE THREAD

**Issue by justinedelson** [adobe/aio-cli-plugin-cloudmanager#233]
### Expected Behaviour

The plugin should more clearly report problems with the ims context configuration, e.g. missing fields, missing metascopes.

### Actual Behaviour

There's a somewhat obscure message `Cannot generate token because no plugin supports configuration`.

### Reproduce Scenario (including but not limited to)

One scenario is doing the two configuration steps in the wrong order. Another is specifying the old JSON for the new configuration key

**Comment by simonfr77** [comment]
Hi @justinedelson - hoping you can help me. This new hook (inc update in 1.3.1) appears to result in errors even when configuring aio. For example consider the following sequence of events: 
- install aio
- install aio-cli-plugin-cloudmanager

We then go on to configure the default IMS context with : 
`aio config:set ims.contexts.aio-cli-plugin-cloudmanager` 
`aio config:set ims.contexts.aio-cli-plugin-cloudmanager.private_key`
`aio config:set cloudmanager_programid`
However, on each attempt to configure the default IMS context we get : 
`There is no IMS context configuration defined for 
 ›   ims.contexts.aio-cli-plugin-cloudmanager.`

This implies to me that the hook is running but doesn't pass validation because the configuration has not yet been applied. Even running `aio plugins` or `aio config:list` results in the same error. 
Is this expected behaviour?

**Comment by justinedelson** [comment]
> Is this expected behaviour?

Definitely not.

Can you create a separate issue for this and I'll get it fixed ASAP.

**Comment by simonfr77** [comment]
Thanks - will raise one now.

**Comment by simonfr77** [comment]
1.3.2 resolved the issue I flagged here in the comments. Thank you.
