### ISSUE TITLE
aio cloudmanager:start-execution: Authorization Error

### ISSUE THREAD

**Issue by AlexVeligosha** [adobe/aio-cli-plugin-cloudmanager#274]
I am using Jenkins and **aio** CLI to run **Adobe Code Quality Pipeline** on schedule.
In general, it works well but sometimes I am receiving an error regarding the Authentication (`Oauth token is not valid`). Restarting the Jenkins job helps with it and the Pipeline starts as expected. 

Could you help with it? Why does it happen from time to time?

### Expected Behaviour
The Code Quality pipeline starts as expected

### Actual Behaviour
```
aio cloudmanager:start-execution XXXXXXX --programId=XXX
 ›   Warning: @adobe/aio-cli update available from 5.0.1 to 6.0.0.
 ›   Run npm install -g @adobe/aio-cli to update.
starting execution... [CloudManagerSDK:ERROR_LIST_PROGRAMS] Cannot retrieve programs: https://cloudmanager.adobe.io/api/programs (401 Unauthorized) - Detail: Oauth token is not valid (Code: 401013)
```

#### Steps to Reproduce
sh 'aio cloudmanager:start-execution ${PIPELINE_ID} --programId=${PROGRAM_ID}'

**Comment by justinedelson** [comment]
Error code 401013 is a fairly generic error code that can either mean that the generated access token has expired or that the technical account is no longer allowed to use the API. It is also possible that a transient error has occurred in the validator. I'm not sure what happens when the job is restarted -- does this reset the configuration somehow? The token is automatically refreshed if it is about to expire (see https://github.com/adobe/aio-lib-ims/blob/da5f8e03a2bfaf0e8d4158e2d44768cff28ccfca/src/token-helper.js#L173-L181). You could also verify this if you look at the access token's expiration date *after* getting this error message.

One thing you could try is to clear out any "old" access token prior to executing the `start-execution` command with:

```
 aio config:del ims.contexts.aio-cli-plugin-cloudmanager.access_token
```

If that helps, we could add a new option to the CLI that forces this to occur.

**Comment by justinedelson** [comment]
@AlexVeligosha any update on this?

**Comment by justinedelson** [comment]
Closing due to no feedback
